import type { Metadata } from "next";
import { Saira, Saira_Condensed } from "next/font/google";
import "./globals.css";

const sairaSans = Saira({
  variable: "--font-saira-sans",
  subsets: ["latin"],
});

const sairaMono = Saira_Condensed({
  variable: "--font-saira-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sairaSans.variable} ${sairaMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
